<%= form_with(model: @security, local: true) do |form| %>
  <% if @security.errors.any? %>
  <div class="lert alert-danger py-3 px-3 my-3">
    <div id="error_explanation">
      <h2>Los siguientes errores han evitado cumplir la tarea:</h2>

      <ul>
        <% @security.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Nombre de la arl' %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address, class: 'form-control', placeholder: 'Digite la direccion' %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_area :phone, class: 'form-control', placeholder: 'Digite el telefono' %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>